const Skills = () => {
  return (
    <>
      <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Amet ullam fugiat repellat soluta ex commodi sed qui exercitationem ea corporis, neque et ducimus minima ipsam ipsum officiis suscipit nihil. Ullam non magnam maxime, deserunt sequi sapiente! Iure molestiae ex obcaecati recusandae provident, minus impedit mollitia praesentium necessitatibus dolor ea quo facilis corrupti deleniti eaque earum dignissimos molestias itaque! Cum amet dolorem dolores soluta magni ipsum, reiciendis incidunt, temporibus laboriosam fugiat ullam consequatur dicta rem saepe fugit corporis autem neque architecto adipisci earum nisi omnis! Cum aliquid, laboriosam atque culpa rerum, omnis a qui sed, itaque ipsum repudiandae. Laudantium labore est delectus velit, ut ab tempora molestiae sunt nemo fuga? Sunt vero autem ipsa, quia, corporis alias nesciunt illo soluta error ipsam ab reprehenderit aspernatur expedita molestias quisquam vel qui eos. Voluptatum delectus voluptates in rerum error obcaecati expedita et cupiditate velit, illum asperiores earum unde eum aliquam eveniet! Molestias velit rem laudantium quaerat dolorum voluptas itaque repudiandae. Sed dicta molestiae voluptas sequi dolor placeat vitae suscipit, nulla quo nesciunt cupiditate cum deleniti expedita sint libero totam perspiciatis commodi esse quisquam. Aut similique, nemo delectus atque, et quis, ab fuga id possimus cupiditate repellendus molestiae voluptate itaque alias vel ipsa hic distinctio quod recusandae omnis aperiam sequi suscipit. Est, officia quia tempore beatae enim doloribus hic vel! Quisquam sapiente cupiditate iure! Corrupti totam voluptatem cumque cupiditate iusto! Veritatis harum ullam fugiat, nulla assumenda earum alias odio accusantium distinctio, ipsa dolor maxime quas quasi totam minus inventore reiciendis deleniti fuga. Autem doloribus dolores veniam, nam asperiores alias illum porro velit accusantium at ducimus recusandae distinctio nostrum! Nemo maxime deleniti quaerat laboriosam quam nulla consequatur ipsa, fuga saepe, animi ab optio at error consequuntur voluptas architecto quae recusandae corporis natus explicabo tempora repudiandae officia. Laborum atque fugiat repellendus illum commodi culpa iure est?</p>
    </>
  )
}

export default Skills
